fiap.web/ViewModels/HomeViewModel.cs
namespace fiap.ViewModels
{
    public class HomeViewModel
    {
        public string NomeDoAluno { get; set; }
        public string CategoriaDoProduto { get; set; }
    }
}

fiap.web/ViewModels/LoginViewModel.cs
namespace fiap.ViewModels
{
    public class LoginViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsPersistent { get; set; }
    }
}

fiap.web/Controllers/AccountController.cs
using fiap.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace fiap.Controllers
{
    public class AccountController : Controller
    {

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Musicas");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                //procurar no banco
                if (model.UserName == "murilo" && model.Password == "123Mudar")
                {
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Name, model.UserName));
                    claims.Add(new Claim(ClaimTypes.Hash, model.UserName));

                    claims.Add(new Claim(ClaimTypes.Role, "admin"));

                    var id = new ClaimsIdentity(claims, "password");
                    var principal = new ClaimsPrincipal(id);

                    await HttpContext.SignInAsync("fiap", principal,
                        new AuthenticationProperties() { IsPersistent = model.IsPersistent });

                    return LocalRedirect("/musicas/create");

                }

            }

            return View(model);
        }



        public async Task<IActionResult> LogOff()
        {
            //remover fingerprint do navegador do banco
            await HttpContext.SignOutAsync();

            return LocalRedirect("/");
        }
    }
}

fiap.web/Controllers/HomeController.cs
using fiap.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace fiap.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["aluno"] = $"Ana Lucia {DateTime.Now.ToString()}";

            ViewBag.TipoDoProduto = "Tenis";

            //origem do banco
            ViewBag.Tentativa = "<script>alert('teste');</script>";

            //return View("Produto");

            //abstraindo o acesso ao banco
            var homeModel = new HomeViewModel();
            homeModel.CategoriaDoProduto = "Calcados";
            homeModel.NomeDoAluno = "Caio";

         
            return View(homeModel);
        }

        public IActionResult Detalhe(string categoria, int idDoProduto, string tamanho)
        {
            
            return View("Produto");
        }
        
        
        [HttpPost]
        public IActionResult Produto(HomeViewModel model)
        {
            return View();
        }


        public IActionResult Login(string returnUrl)
        {
            if (!Url.IsLocalUrl(returnUrl))
            {
                return LocalRedirect("/");

            }
            else
            {

                return LocalRedirect(returnUrl);
            }

            //return LocalRedirect(returnUrl);
        }

    }
}

fiap.web/Controllers/MusicasController.cs
using fiap.domain.Models;
using fiap.persistence.Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;

namespace fiap.Controllers
{

    [Authorize]
    public class MusicasController : Controller
    {
        private MusicaContext _context;

        public MusicasController(MusicaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var teste = User;
            var musicas = _context.Musicas.ToList();

            return View(musicas);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] Musica model)
        {
            if (ModelState.IsValid)
            {
                //salva no banco
                _context.Musicas.Add(model);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }


            return View(model);
        }


        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var musica = _context.Musicas.Find(Id);

            return View(musica);
        }

        [HttpPost]
        public IActionResult Edit([FromForm] Musica model)
        {
            if (ModelState.IsValid)
            {
                _context.Update(model);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int Id)
        {
            return View(_context.Musicas.First(a => a.Id == Id));
        }

        [HttpGet]
        [Authorize(Roles ="admin")]
        public async Task<IActionResult> Delete(int Id)
        {
            #region exemplos tasks
            //var musica = _context.Musicas.Single(a => a.Id == Id);
            //Select top 2 * from musicas where id =1

            //var musica1 = _context.Musicas.SingleOrDefaultAsync(a => a.Id == Id + 1);
            //var musica2 = _context.Musicas.SingleOrDefaultAsync(a => a.Id == Id + 2);
            //var musica3 = _context.Musicas.SingleOrDefaultAsync(a => a.Id == Id + 3);

            //List<Task> tasks = new List<Task>() { musica, musica1, musica2, musica3 };

            //Task.WaitAll(tasks.ToArray());
            //Task.WaitAny(tasks.ToArray());
            ////null

            //var musica = _context.Musicas.First(a => a.Id == Id);
            ////select top 1

            //var musica = _context.Musicas.FirstOrDefault(a => a.Id == Id);
            ////null
            #endregion

            var musica = await _context.Musicas.SingleOrDefaultAsync(a => a.Id == Id);
            if (musica != null)
            {
                _context.Musicas.Remove(musica);
                // _context.SaveChanges();
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");

            }


            return new NotFoundResult();
        }
    }
}

fiap.web/ViewComponents/NoticiasViewComponent.cs
using fiap.application.Services;
using Microsoft.AspNetCore.Mvc;

namespace fiap.ViewComponents
{
    public class NoticiasViewComponent : ViewComponent
    {
        private INoticiaService _noticiaService;

        public NoticiasViewComponent(INoticiaService noticiaService)
        {
            _noticiaService = noticiaService;

        }
        public async Task<IViewComponentResult> InvokeAsync(int total, bool noticiasUrgentes)
        {
            var noticias = _noticiaService.Load(total);
            
            var viewName = "Noticias";

            if (noticiasUrgentes)
            {
                viewName = "NoticiasUrgentes";
            }

            return View(viewName, noticias);
            
        }
    }
}

fiap.web/Views/Home/Index.cshtml
@model HomeViewModel




<section class="jumbotron text-center">
    <div class="container">
<<<<<<< HEAD
        <h1 class="jumbotron-heading">Teste do Deploy v4</h1>
=======
        <h1 class="jumbotron-heading">Tript Azure V2</h1>
>>>>>>> d7bf0765b529fb8e111deedcc5ad5016c8f23fee
        <p class="lead text-muted">Conheca as novidades sobre os melhores destinos e esteja sempre por dentro das novidades.</p>
        <p>
            <a href="#" class="btn btn-primary my-2">Buscar passagens</a>
            <a href="#" class="btn btn-secondary my-2">Conheca nosso blog</a>
        </p>
    </div>
</section>


<div class="row">
    <div class="menu">
        <ul>
            <li>
                <div class="mysprite alemanha"  ></div>
            </li>
            <li>
                <div class="mysprite brasil"></div>
            </li>
            <li>
                <div class="mysprite argentina"></div>

            
            </li>
            <li>
                <div class="mysprite japao"></div>

            </li>
            <li>
                <div class="mysprite espanha"></div>

            </li>
            <li>
                <div class="mysprite grecia"></div>

            </li>
            <li>
                <div class="mysprite eua"></div>

            </li>
            <li>
                <div class="mysprite italia"></div>

            </li>
            <li>
                <div class="mysprite portugal"></div>

            </li>
           
        </ul>
    </div>
</div>


<div class="row">
    <div id="carroseul" class="col">
        <div class="jcarousel-wrapper">
            <div class="jcarousel">
                <ul>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-1.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-2.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-3.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-4.jpg" />
                    </li>
                </ul>
            </div>
            <div>
                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
            </div>

        </div>
    </div>
</div>


<vc:noticias total="20" noticias-urgentes="false"></vc:noticias>

fiap.web/Views/Home/Produto.cshtml
@{
    //Layout = "_NovaLayout";
    Layout = null;
}



<h1>Teste da view de produto</h1>

fiap.web/Views/Musicas/Create.cshtml
@model Musica

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Musica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="create">
           @* @Html.AntiForgeryToken()*@
          


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tempo" class="control-label"></label>
                <input asp-for="Tempo" class="form-control" />
                <span asp-validation-for="Tempo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banda" class="control-label"></label>
                <input asp-for="Banda" class="form-control" />
                <span asp-validation-for="Banda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstiloMusical" class="control-label"></label>
                <input asp-for="EstiloMusical" class="form-control" />
                <span asp-validation-for="EstiloMusical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

fiap.web/Views/Musicas/Details.cshtml
@model Musica

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Musica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tempo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tempo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Banda)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Banda)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstiloMusical)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstiloMusical)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

fiap.web/Views/Musicas/Edit.cshtml
@model Musica

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Musica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tempo" class="control-label"></label>
                <input asp-for="Tempo" class="form-control" />
                <span asp-validation-for="Tempo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Banda" class="control-label"></label>
                <input asp-for="Banda" class="form-control" />
                <span asp-validation-for="Banda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstiloMusical" class="control-label"></label>
                <input asp-for="EstiloMusical" class="form-control" />
                <span asp-validation-for="EstiloMusical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

fiap.web/Views/Musicas/Index.cshtml
@model IEnumerable<Musica>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tempo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Banda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Album)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstiloMusical)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tempo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Banda)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Album)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstiloMusical)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

fiap.web/Views/Shared/Components/Noticias/Noticias.cshtml
@model List<Noticia>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top lazy" data-src="@item.Imagem">
                            <div class="card-body">
                                <p class="card-text">@item.Titulo</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                    </div>
                                    <small class="text-muted">ultima atualizacao @item.UltimaAtualizacao</small>
                                </div>
                            </div>
                        </div>
                    </div>
            }

        </div>
    </div>
</div>

fiap.web/Views/Shared/Components/Noticias/NoticiasUrgentes.cshtml
@model List<Noticia>

<ul>
    @foreach (var item in Model)
    {
        <li style="background-color:red;">
            <a href="@item.Link">@item.Titulo</a>
        </li>
    }
</ul>

fiap.web/Views/Shared/_Layout.cshtml
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    @* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="~/jcarousel.basic.css" />
    <link rel="stylesheet" href="~/site.css" asp-append-version="true" />*@

    <link rel="stylesheet" href="~/bundle.min.css" asp-append-version="true" />
   


    
  
    
    

</head>
<body>
    <div>
       
        @*@Html.Partial("_Menu")
        
        
        @await Html.PartialAsync("_Menu")
        *@
        
        <partial name="_menu" ></partial>
        

        <article>
            @RenderBody()
        </article>


    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/jquery.jcarousel.min.js"></script>
    <script src="~/jquery.lazy.min.js"></script>
    <script src="~/site.js"></script>
    <script>
        $(function () {
            $('.lazy').lazy();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

fiap.web/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

    <div class="container-fluid">
        <a class="navbar-brand" href="/"> Fiap 2023</a>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark"
                       href="/"> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark"
                       href="/time"> Times</a>
                </li>
            </ul>
        </div>
    </div>
</nav>